### ISSUE TITLE
Scope configuration not respected on login

### ISSUE THREAD

**Issue by Vincentjonssonqi** [yubozhao/meteor-accounts-instagram#15]
Even when I specify that I want the scope to be public_content the authorization url includes scope=likes+comments+relationships+basic. It is like my scope config is entirely ignored.

**Comment by Nomeasmo** [comment]
The library is prepared for it but it's not documented. Search your code for ` Meteor.loginWithInstagram` and add  your permissions to the options `requestPermissions: ['basic', 'public_content', 'likes', 'relationships', 'comments']`.

e.g.:
```js
      Meteor.loginWithInstagram({
        loginStyle: 'popup',
        requestPermissions: ['basic', 'public_content', 'likes', 'relationships', 'comments']

        //loginStyle: 'redirect'  you can use redirect for mobile web app
      }, function () {
        console.log('in call back', arguments);
      });
```

**Comment by yubozhao** [comment]
@Nomeasmo Thank you for answering!  Sorry didn't check out my notifications in github.
