### ISSUE TITLE
loginWithInstagram returns undefined

### ISSUE THREAD

**Issue by kontur** [yubozhao/meteor-accounts-instagram#7]
Hey,

in the README example step 6) you're using:

    Meteor.loginWithInstagram(function (err, res) {
          if (err !== undefined)
            console.log('sucess ' + res)
          else
            console.log('login failed ' + err)
      });

This will output `login failed` also when the login succeeded, because both `err` and `res` are undefined.

From what I can tell, the function never returns anything: https://github.com/yubozhao/meteor-accounts-instagram/blob/master/instagram.js

I am not that familiar with the accounts system, but I suppose this might be an easy fix - or amend to the README omitting this instruction, at the very least :)

Thanks for the great package!

**Comment by yubozhao** [comment]
@kontur 

Thank you for reporting issue!   I will take a look to see where the issue is, and will fix it sometime in this week.

**Comment by jsamos** [comment]
any progress here?

**Comment by yubozhao** [comment]
@jsamos   @kontur  I checked my code, it is an example error.   It is inline of Meteor's other login format, which is it only return error, if there is one.

**Comment by kontur** [comment]
So, the issue is closed but the codebase didn't change, what's the outcome here? :)

**Comment by yubozhao** [comment]
@kontur It is an example error.  It is following Meteor's login pattern. for other services.    Which is if there is an error, it will return error, otherwise, nothing is returned.

I will update the readme file in the next release.
