### ISSUE TITLE
default icon

### ISSUE THREAD

**Issue by malcolmevans** [yubozhao/meteor-accounts-instagram#8]
Thanks so much for writing this package, @yubozhao, super helpful! 

Is it possible to change the default image that comes with the login button when the accounts-ui package is in use? Right now its an S of some sorts (see attached).

Thanks!

![screen shot 2015-04-06 at 2 10 11 am](https://cloud.githubusercontent.com/assets/4626262/7001210/1e2440b8-dc02-11e4-8ad4-597a327d272f.png)

**Comment by yubozhao** [comment]
@malcolmevans Yep  I will change it.

**Comment by malcolmevans** [comment]
Thanks!
